// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1OTJnUGkymJ-F8byRWexjPDu6fMcAUEk',
    appId: '1:1090732589984:web:c9f6ed2ba67f81e92c9ac5',
    messagingSenderId: '1090732589984',
    projectId: 'recipe-app-ce154',
    authDomain: 'recipe-app-ce154.firebaseapp.com',
    storageBucket: 'recipe-app-ce154.firebasestorage.app',
    measurementId: 'G-ZXZG56M4L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKdjw5ZKt51v8FyscWR5ZQiNYs3Puol08',
    appId: '1:1090732589984:android:9c993b3370d1ae9b2c9ac5',
    messagingSenderId: '1090732589984',
    projectId: 'recipe-app-ce154',
    storageBucket: 'recipe-app-ce154.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxkm0fSjxL_Eael73jbrlVcQKorXNvRhg',
    appId: '1:1090732589984:ios:28c1b0c34ba156cf2c9ac5',
    messagingSenderId: '1090732589984',
    projectId: 'recipe-app-ce154',
    storageBucket: 'recipe-app-ce154.firebasestorage.app',
    iosBundleId: 'com.example.learnBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxkm0fSjxL_Eael73jbrlVcQKorXNvRhg',
    appId: '1:1090732589984:ios:28c1b0c34ba156cf2c9ac5',
    messagingSenderId: '1090732589984',
    projectId: 'recipe-app-ce154',
    storageBucket: 'recipe-app-ce154.firebasestorage.app',
    iosBundleId: 'com.example.learnBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1OTJnUGkymJ-F8byRWexjPDu6fMcAUEk',
    appId: '1:1090732589984:web:8c3a8fa9db09e56f2c9ac5',
    messagingSenderId: '1090732589984',
    projectId: 'recipe-app-ce154',
    authDomain: 'recipe-app-ce154.firebaseapp.com',
    storageBucket: 'recipe-app-ce154.firebasestorage.app',
    measurementId: 'G-TGWC8M3C94',
  );
}